### PR TITLE
Updating Dependencies

### PR DESCRIPTION
**Pull request by nicholasio**
### Checklist:

- [ ] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests passed.

### Changelog Entry

10up-toolkit:

- Updated several dependencies.
- Updated to postcss-preset-env 7.0 and switched from postcss-nested to postcss-nesting (BREAKING CHANGE)
- Disable polyfill for CSS custom properties.
- Removed wordpress/jest-preset-default and now shipping a custom jest config. Jest was also updated to the latest version.

babel-preset-default:
- Updated dependencies

eslint-config
- Updated dependencies

stylelint-config
- updated dependencies

### CODE REVIEW

**Comment by nicholasio** [comment]
@Antonio-Laguna @rdimascio I've updated postcss and added some basic snapshot tests. https://github.com/10up/10up-toolkit/pull/114/files#diff-804253cfe6fd1bea7bee566ae02a5a0c8253e0385671a454e1339e33c533f243R41

Can you help me give some more examples of postcss syntax and help me validate the output?

**Comment by Antonio-Laguna** [comment]
@nicholasio nice work!

Glancing at that I think it covers what we usually do in any project. Having this to test against every single thing that `postcss-preset-env` covers for wouldn't probably be ideal given that every library has its own tests already and the packer (preset-env) has also more tests.

As a pie in the sky request, I love the snapshots but I don't love how crammed they look. If you were to spot a difference in a single line of CSS you're going to have a bad time.

**Comment by nicholasio** [comment]
> @nicholasio nice work!
> 
> Glancing at that I think it covers what we usually do in any project. Having this to test against every single thing that `postcss-preset-env` covers for wouldn't probably be ideal given that every library has its own tests already and the packer (preset-env) has also more tests.
> 
> As a pie in the sky request, I love the snapshots but I don't love how crammed they look. If you were to spot a difference in a single line of CSS you're going to have a bad time.

Yep I agree I'll see if I can tweak postcss output to be more readable.

**Comment by nicholasio** [comment]
@Antonio-Laguna Done. can you check the snapshots for the CSS tests? I'm not sure if nesting output is correct.

**Comment by rdimascio** [comment]
@nicholasio It looks like this is the expected output based on the tests in `postcss-nesting` https://github.com/csstools/postcss-nesting/blob/4645fdf69cbd0592cde8f9c76427ed7ec7b6725a/test/direct.expect.css#L4

**Comment by Antonio-Laguna** [comment]
@nicholasio nice one! This looks so much better and if ever needs to change it'll be more obvious!

As @rdimascio points the nesting is as spec so it looks fine to me.

Not sure how you feel about this but I wanted to suggest avoiding preserving custom-variables notation given that [support](https://caniuse.com/css-variables) is over 96%. Not really sure how you feel about that but it should look like this:

```js
'postcss-preset-env': {
  stage: 0,
    autoprefixer: {
    grid: true,
  },
  features: {
    'nesting-rules': {
      preserve: false,
    },
  },
},
```

I feel given we're using custom properties more and more this leads to bloating the output CSS for little gain but it's a controversial change.

**Comment by rdimascio** [comment]
@Antonio-Laguna Great point, especially considering we're dumping IE support. If we do it now then we would avoid having to release another breaking change.

cc @joesnellpdx @devinle @Firestorm980 @fabiankaegy

**Comment by nicholasio** [comment]
FYI I'll also include a breaking change to fully disable IE11 support in 10up-toolkit

**Comment by rdimascio** [comment]
Gotcha, then it would make more sense to include @Antonio-Laguna's suggestion in that future release.

**Comment by nicholasio** [comment]
I'll defer to @joesnellpdx and @devinle

**Comment by devinle** [comment]
@nicholasio @Antonio-Laguna @rdimascio thanks for the quick explanation Ryan. I think, since IE 11 support is being removed, it makes sense to also make the custom properties update. As you all mention, this will already be a breaking change, and ridding of this bloat is another awesome side effect of losing IE 11 support. You have my vote here.  @joesnellpdx anything to add?

**Comment by nicholasio** [comment]
@Antonio-Laguna You mentioned custom properties but your example is referencing `nesting-rules`. Is that right? Or do you mean `custom-properties`? When I disable polyfills for custom-properties it seems to be removing all references to custom properties.

UPDATE:

nvm I think I figure it out, the config needed is 
```javascript
	'postcss-preset-env': {
		stage: 0,
		autoprefixer: {
			grid: true,
		},
		features: {
			'custom-properties': false,
		},
	},
```

**Comment by devinle** [comment]
@nicholasio good callout. That was my assumption as well. Looks like with that reference, you could do the same thing for custom properties.

To be clear, this change also wouldn't support BEM nesting, correct? I'm not opposed to not supporting this, just want to be clear.

`.parent {
    &__child {
        ...
    }
}
`

Don't let this comment hold a merge up though. I'm fine with it. Just for my own understanding. I don't know that we even support this currently.

**Comment by joesnellpdx** [comment]
To clarify from my end...

@Antonio-Laguna 
I assume I am correct in that we are disabling polyfills for custom properties. This makes sense to me (`'custom-properties': false`), as support for native custom properties are supported by modern browsers. We can use class scoped custom properties without issue (so long as browsers support). 

@devinle @Antonio-Laguna @rdimascio 
I also assume the nesting rules stay the same EXCEPT for classname extensions (i.e. BEM) per @devinle 's message.
I'm fine with that too per best practices as I find full classnames to be more readable. 

BEM classname extensions (what is being disabled and will no longer work)
```
.parent {
     // styles
     &__child {
          // styles
     }
}
```

Preferred: 
```
.parent {
     // styles
}

.parent__child {
     // styles
}
```

Are there other breaking changes I may not be aware of? I do not have time to fully vet this. 

This, however, is a breaking change. So, agreed it a breaking change sem ver is needed and a team summary should be posted once the collection of all these updates are complete (which I'm assuming is part of the plan)

@nicholasio

**Comment by Antonio-Laguna** [comment]
@nicholasio @rdimascio @devinle @joesnellpdx 

Apologies for my first snippet. My only suggestion was for custom properties and not nesting as that's still a draft and not supported by any browser I was fixated on the nesting question and used the wrong key! 

As per nesting It's the only thing I can see being breaking.

**Comment by nicholasio** [comment]
Sounds good. I'll merge this PR then and get a few other things in before releasing 2.0

**Pull request merged**
