### PR TITLE
feat: drop squosh in favor of sharp for optimizing images

### LINKED ISSUE #220: Consider dropping Squoosh
### Is your enhancement related to a problem? Please describe.

Squoosh is mostly experimental and doesn't really get much attention from the Google team. It's been a year since their last release and issues are piling up as well as pull requests.

They don't support Node 18 which IMHO is a deal breaker too since it'll be LTS 

See https://github.com/GoogleChromeLabs/squoosh/issues/1265 and https://github.com/GoogleChromeLabs/squoosh/issues/1265

### Designs

_No response_

### Describe alternatives you've considered

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by nicholasio**
Related Issue/RFC: #220 

### Description of the Change

Removes squoosh in favor of a custom implementation of a image optimizer using sharp.

### Possible Drawbacks

The results are obviously gonna be different and probably images will not be compressed as much as before.

### Verification Process

`cd projects/10up-theme && npm run build`

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.
- [x] I have added a changeset to my PR. See [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document for instructions

### CODE REVIEW

**Comment by Antonio-Laguna** [comment]
@nicholasio I think this is great! Nice work!

I'm wondering if it should be behind a flag so it can be tested on real environments so we ping those who have had issues (such as what recently popped in slack) or perhaps just with the `next` release is fine before making the general change? I just fear it breaks on CI and we have to find yet-another-minifier. 

Thoughts?

**Comment by nicholasio** [comment]
> @nicholasio I think this is great! Nice work!
> 
> I'm wondering if it should be behind a flag so it can be tested on real environments so we ping those who have had issues (such as what recently popped in slack) or perhaps just with the `next` release is fine before making the general change? I just fear it breaks on CI and we have to find yet-another-minifier.
> 
> Thoughts?

We can do a next release, I don't think we need a flag for this. I'd consider this an implementation detail and not something projects would need to worry about how images are being optimized. I was also thinking of just releasing this as a minor update. Thoughts? Concerns?

For those disabling squosh, they will keep disabling this new implementation and there's no way for projects to customize image optimization params so I don't see how this could be a breaking change.

**Comment by Antonio-Laguna** [comment]
I don't think it's breaking as intended to be breaking but our tests are reduced and not in the wild with N images with perhaps reduced memory so what works now might not work later. So you release a minor version but inadvertently create issues that weren't there before. 

IMHO if `next` is released and works OK for those who have it failing then it's safe enough to bump to minor.

**Review by Antonio-Laguna — APPROVED** [review]
This LGTM! Nice one! Can't wait to get this somewhat tested!

**Comment by Antonio-Laguna** [comment]
Can you add this closes #212 and also fixes #220 ?

**Comment by Antonio-Laguna** [comment]
Looks like it just happened :/ though not with #212 which is fine

**Pull request merged**
