### PR TITLE
HMR and Fast Refresh

### LINKED ISSUE #85: Hot Module Replacement and React Fast Refresh
**Is your enhancement related to a problem? Please describe.**
We currently use BrowserSync but it has many limitations. Currently, it's not working well; see #62 and even when we get it working right, we would still need to reload the browser to reflect JS changes.

After spending some time playing with BrowserSync and webpack I actually thought it would be more interesting to set up webpack-dev-server to proxy WordPress (based on the existing devURL setting) and implement Hot Module Replacement and React Fast refresh.

10up-toolkit already ships webpack-dev-server but's it's only used in package mode: https://github.com/10up/10up-toolkit/blob/develop/packages/toolkit/scripts/start.js#L41

**Describe the solution you'd like**
- HMR for vanilla JS.
- React Fast Refresh for react code  and Gutenberg

**Designs**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by nicholasio**
### Description of the Change

Closes #85 

This PR introduces React Fast Refresh for block development and Hot Module Reloading for front-end css.

react-fast-refresh-toolkit
### Alternate Designs

Refresh the browser every time you make a change to a block.

### Possible Drawbacks

Not every code change can be reloaded without a refresh. Based on my quick tests, changing `registerBlockType` args causes a full page reload. However, for most of the block development, fast refresh should work fine.

This change is fully backward compatible and is only effective if you pass the `hot` option.

~Unfortunately, BrowserSync is still required as this setup only works for block development. Hopefully, in the future we can get rid of BrowserSync in favor of HMR.~

We can now deprecate BrowserSync.

### Verification Process Option 1 (Installing from npm)

Docs are also available here: https://github.com/10up/10up-toolkit/tree/feature/fast-refresh/packages/toolkit#fast-refresh

- Install `10up-toolkit@2.2.0-alpha.4` via npm.
- Run `10up-toolkit watch --hot` or if using the wp-scaffold `npm run watch -- --hot`
- Set `SCRIPT_DEBUG` to `true`
- Open up `functions.php` or the entry point of your plugin and add the following snippet of code (replace the constants with the URL and PATH to dist folder):
  - https://github.com/10up/10up-toolkit/blob/feature/fast-refresh/projects/10up-theme/functions.php#L17
```php
if ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG && file_exists( __DIR__ . '/dist/fast-refresh.php' ) ) {
	define( 'TENUP_TOOLKIT_DIST_URL', TENUP_THEME_DIST_URL );
	define( 'TENUP_TOOLKIT_DIST_PATH', TENUP_THEME_DIST_PATH );
	require_once __DIR__ . '/dist/fast-refresh.php';
}
```
Make sure to reload the page after running 10up-toolkit as the `dist/fast-refresh.php` file is generated by 10up-toolkit

### Verification Process Option 2 (using this repo)
- This has only been tested with Chrome! Let me know if it works on other browsers.
- Clone this repo and switch to this branch
  - `git clone git@github.com:10up/10up-toolkit.git && cd 10up-toolkit && git checkout feature-fast-refresh`
  - From the root dir, run `npm install`
- Create or use an existing WordPress environment form where you can run `projects/10up-theme`. If you are using `wp-local-docker` you can map the path to `projects/10up-theme` to your containers

Nginx container:
```yaml
  nginx:
    .....
    volumes:
      - './wordpress:/var/www/html:cached'
      - '~/projects/10up-toolkit/projects/10up-theme:/var/www/html/wp-content/themes/10up-theme'
      - './config/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached'
```

phpfpm container:
```yaml
phpfpm:
    ....
    volumes:
      - './wordpress:/var/www/html:cached'
      - '~/projects/10up-toolkit/projects/10up-theme:/var/www/html/wp-content/themes/10up-theme'
      - './config/php-fpm/docker-php-ext-xdebug.ini:/etc/php.d/docker-php-ext-xdebug.ini:cached'
      - 'wplocaldockerCache:/var/www/.wp-cli/cache:cached'
      - '~/.ssh:/home/nicholas_io/.ssh:cached'
      - './config/php-fpm/wp-cli.local.yml:/var/www/.wp-cli/config.yml:cached'
```

Replace `~/projects/10up-toolkit/projects/10up-theme` with the path to your local version of `10up-toolkit/projects/10up-theme`
- Set `SCRIPT_DEBUG` to true in `wp-config.php`
- Go to Appearance -> Themes and enable the "10up theme"
- Go to `10up-toolkit/projects/10up-theme` and run `npm run watch -- --hot`
- Go to any post or page and add the "Example Block"
- Try making changes to in `includes/blocks/example-block/edit.js` and `includes/blocks/example-block.css` you should see changes in real-time.
  -  The first "reload" is a little slower.

NOTE: if you have the Gutenberg plugin enabled you might see an error about service worker registration, just close that overlay and keep testing.
### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Changelog Entry

Added - React Fast Refresh for block development (BETA)
### Credits

This was heavily based on https://github.com/WordPress/gutenberg/pull/28273

The approach here was extended a bit and 10up-toolkit does not actually require running the Gutenberg plugin.

Props @

### CODE REVIEW

**Comment by nicholasio** [comment]
A couple of notes:
 - [x] Add phpcs ignore to the generated `fast-refresh.php` file.
 - [x] When leaving "hot" mode, the compiled assets will have the fast refresh instrumentation and therefore the js will keep trying to talk to webpack-dev-server. This might be a bit confusing, we might want to introduce a "shutdown" phase to toolkit that would clean up dist folder or recompile the assets without the fast refresh instrumentation
 - It looks like all of the webpack warnings are showing up on the overlay, not sure if we want webpack warnings from eslint and styleling to show up or even cause errors in the browser
 
image
~I think ideally warnings should not show up in the browser overlay, only js errors that would prevent compiling.~

UPDATED: This seems to be a common behavior, and these warnings/errors from eslint don't prevent the code from running and I think it provides a good feedback loop to engineers.

**Comment by nicholasio** [comment]
I actually got this working on the front-end for regular CSS. It requires loading the CSS entry point through a JS entry point instead of making the CSS an entry point of its own (~This hasn't been released to npm yet~ release in `10up-toolkit@2.2.0-alpha.2`).

Changing any JS loaded on the front-end causes a full page refresh.

hmr-front-end

**Comment by fabiankaegy** [comment]
Some things I've noticed in testing:
- HMR does not work in Safari 
- CSS Errors also take over the entire editor screen with a warning:
CleanShot 2022-02-24 at 18 30 31@2x
- CSS changes that happen in the `theme/assets/css/frontend/editor-style.css` don't get hot reloaded in the editor.

**Comment by gziolo** [comment]
Hello, it's so nice to see this integration being exercised :+1:

I have a few pointers that might help:

> Not every code change can be reloaded without a refresh. Based on my quick tests, changing registerBlockType args causes a full page reload. However, for most of the block development, fast refresh should work fine.

Yes. I discovered the same issue. It looks like only files with React components get refreshed without the full page reload, but it's possible to work around it as summarized in this comment:
https://github.com/WordPress/gutenberg/pull/28273#issuecomment-1023340680

> HMR does not work in Safari

There are no React Developer Tools for Safari so it's harder to configure it. React Refresh entry and runtime needs to be externalized and initialized before React loads (https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#externalising-react). At the moment it's only available with the Gutenberg plugin enabled and `SCRIPTS_DEBUG` set to `true` that ensures that the React Refresh runtime is correctly configured. In Chrome, it should work with the Gutenberg plugin enabled and it probably doesn't need the React Refresh runtime.

**Comment by nicholasio** [comment]
@gziolo Thank you for following up and for all the hard work you did on getting this into Gutenberg.

> Yes. I discovered the same issue. It looks like only files with React components get refreshed without the full page reload, but it's possible to work around it as summarized in this comment:
https://github.com/WordPress/gutenberg/pull/28273#issuecomment-1023340680

A babel plugin would be great to work around some of these edges cases. I have little exp with babel plugins but I'm interested in trying this approach out in the future. 

> There are no React Developer Tools for Safari so it's harder to configure it. React Refresh entry and runtime needs to be externalized and initialized before React loads (https://github.com/pmmmwh/react-refresh-webpack-plugin/blob/main/docs/TROUBLESHOOTING.md#externalising-react). At the moment it's only available with the Gutenberg plugin enabled and SCRIPTS_DEBUG set to true that ensures that the React Refresh runtime is correctly configured. In Chrome, it should work with the Gutenberg plugin enabled and it probably doesn't need the React Refresh runtime.

I took a different approach here and our integration doesn't require the Gutenberg plugin. I'm loading `react-refresh-entry` but perhaps I just need to make sure it's running before any react code.

**Comment by gziolo** [comment]
> I took a different approach here and our integration doesn't require the Gutenberg plugin. I'm loading react-refresh-entry but perhaps I just need to make sure it's running before any react code.

That's great. Yes, it needs to load before and I did it in Gutenberg by setting it as a dependency of `react`  😄

https://github.com/WordPress/gutenberg/blob/f833f821105aa7129533fff802937d22f14c3099/lib/client-assets.php#L207-L213 

> A babel plugin would be great to work around some of these edges cases. I have little exp with babel plugins but I'm interested in trying this approach out in the future.

Great thinking, a Babel plugin should do the trick. I saw the following Babel plugin for HRM in Solid library that could be used as an inspiration:

https://github.com/solidjs/solid-refresh/blob/main/babel.js

**Review by fabiankaegy — APPROVED** [review]
I've spent some time testing this and it is working like a charm (in chrome). I think we can merge this in and work on enhancements from there :)

**Comment by gziolo** [comment]
I'm super excited about this integration 🎉 

Let's keep the feedback loop in https://github.com/WordPress/gutenberg/pull/28273 so we can improve how React Fast Refresh integrates with the block editor 😄

**Comment by nicholasio** [comment]
quick note: by settings `https: true` in the dev server, I can get fast refresh to work after trusting the unsigned cert manually. However, I'm not sure if there's a way to just make it work over https/wss protocol. I'll stick to forcing the `ws` protocol for web socket communication for now.

**Comment by gziolo** [comment]
> quick note: by settings `https: true` in the dev server, I can get fast refresh to work after trusting the unsigned cert manually. However, I'm not sure if there's a way to just make it work over https/wss protocol. I'll stick to forcing the `ws` protocol for web socket communication for now.

Not that I know more, but I'm a bit familiar with the webpack docs after working with that for quite some time. There is https://webpack.js.org/configuration/dev-server/#devserverhttps that has some examples of how to update the config or pass some custom data with CLI args.

**Comment by nicholasio** [comment]
I'm going to merge this!

A new release (2.2.0) will be out next week that will include this!

Thanks all for the help on this effort!

I'll do some quick tests to try to get this working on safari and I'll open a separate PR if I managed to get it working.

**Pull request merged**
