### PR TITLE
fix maybe insert style version hash to dist block.json files

### LINKED ISSUE #280: Add dynamic `version` to copied `block.json` files in `dist` folder to ensure block styles bust cashes
Styles defined via `block.json` sadly don't pull a version number from the `.asset.php` file like js files do. Instead, the styles expect a `version` key to be present in the `block.json` file. Maintaining this manually is a real pain and therefore not really an option on projects. Therefore it would be great if we could add a dynamic version number to the `block.json` file.

### PR DESCRIPTION
**Pull request by fabiankaegy**
Related Issue/RFC: #280 

### Description of the Change

If a `block.json` file does not have a `version` defined but loads a local (`file:`) `style` property, we get a content hash of that style file and add that as the version into the `block.json` file. WordPress then uses this version to bust the cache of our stylesheet. 

### Checklist:

- [x] I have read the [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [x] All new and existing tests passed.
- [x] I have added a changeset to my PR. See [**CONTRIBUTING**](https://github.com/10up/10up-toolkit/blob/develop/CONTRIBUTING.md) document for instructions

### CODE REVIEW

**Review by fabiankaegy — COMMENTED** [review]
Thank you for adding tests to cover this change :) I wasn't exactly sure how / where to best add them

**Review by nicholasio — APPROVED** [review]
Great work!

Just added a couple of tests!

**Comment by nicholasio** [comment]
@Antonio-Laguna mind reviewing this one as well?

**Review by Antonio-Laguna — APPROVED** [review]
This looks great! Love the tests too!

**Pull request merged**
